# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PW}
      POSTGRES_USER: chat
      POSTGRES_DB: chat
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  chat:
    image: johannesjahn/chat-api:0.0.2
    command: bash -c "node dist/main.js"
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./.dev.env:/usr/app/.env

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - db
      - adminer
      - chat
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/user_conf.d/server.dev.conf:/etc/nginx/nginx.conf
      - ./static:/home/app/web/
