# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PW}
      POSTGRES_USER: chat
      POSTGRES_DB: chat
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    expose:
      - 8080

  chat:
    image: johannesjahn/chat-api:0.0.6
    command: bash -c "node dist/main.js"
    volumes:
      - ./.env:/usr/app/.env
    expose:
      - 3000

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=johannes.jahn@outlook.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d/server.conf:/etc/nginx/user_conf.d/server.conf
      - ./static:/home/app/web/
