host: chat.johannes-jahn.com
volumeBasePath: /home/nacho/chat-api
images:
  backend: johannesjahn/chat-api:2.1.76
  frontend: johannesjahn/nacho-chat:1.6.44
secrets:
  DB_USER: 'chat'
  DB_PASS: 'chat2'
  DB: 'chat'
  JWT_SECRET: 'JWT_SECRET'
  SALT: '123456789ABCDEFG'
