images:
  backend: johannesjahn/chat-api:2.0.254
  frontend: johannesjahn/nacho-chat:1.5.114
secrets:
  DB_USER: 'chat'
  DB_PASS: 'chat2'
  DB: 'chat'
  JWT_SECRET: 'JWT_SECRET'
  SALT: '123456789ABCDEFG'
