apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: nacho.johannes-jahn.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chat-api
                port:
                  number: 3000
          - path: /adminer
            pathType: Prefix
            backend:
              service:
                name: adminer
                port:
                  number: 8080
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: chat-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls:
    - secretName: nacho.letsencrypt
      hosts:
        - nacho.johannes-jahn.com
